# Generated by Django 3.1.14 on 2022-09-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20220905_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ManyToManyField(null=True, related_name='_pokemon_next_evolution_+', to='pokemon_entities.Pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ManyToManyField(null=True, related_name='_pokemon_previous_evolution_+', to='pokemon_entities.Pokemon'),
        ),
    ]
